build:
  maxIssues: 1

formatting:
  active: true
  android: false
  autoCorrect: false
  FinalNewline:
    active: false
  NoBlankLineBeforeRbrace:
    active: false

style:
  NewLineAtEndOfFile:
    active: false
  MagicNumber:
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreEnums: true